### ISSUE TITLE
[Microsoft Teams] AclCheckFailed 

### ISSUE THREAD

**Issue by jamachad** [Microsoft/BotBuilder-V3#103]
## Version
What package version of the SDK are you using.
3.19.1.44133

## Describe the bug
Calling the method **CreateOrGetDirectConversation** will give the following exception for a subset of users:

**Error Message**: _Operation returned an invalid status code 'Forbidden'._

Additionally, on Bot Services channels, the Microsoft Teams reports multiple occurrences of the following error: **Failure due to: AclCheckFailed.**

This doesn't happen for all users. Also, working and non-working users are part of the same Tenant.

## Expected behavior
To be able to call **CreateOrGetDirectConversation** to initiate a conversation with a user.

## Additional context
Adding a single user as the only team member doesn't work either.
Tried with Microsoft.Bot.Connector.Teams v0.8 and v0.9

[bug]
[dotnet]

**Comment by jwiley84** [comment]
This is not an issue we usually see with Teams; typically it comes up on Skype when it does come up. You say 'to initiate a conversation with a user'. Is your bot trying to send proactive or welcome messages? Also, can you check if the users affected have not blocked the bot via the teams interface?

**Comment by EricDahlvang** [comment]
Closing due to no response.

**Comment by jamachad** [comment]
Sorry, I OOF and couldn't validate the latest comments.
I tried again today and it worked for the rest of users (>60 users). I no longer see the ACLCheckFailed so I assume was something with the platform...
