### ISSUE TITLE
[500 internal error, unauthorized ] Bot error, when to send message to bot via directline.

### ISSUE THREAD

**Issue by rib-pet** [Microsoft/BotBuilder-V3#104]
## Version
What package version of the SDK are you using.
3.15.2.2

## Describe the bug

first of all, I got the direct line secret from my bot services. therefore, in front -end, I try to send the message to my bot. during this process, Direct line always is able to return proper token. however, when to post message to bot. I was informed that 500 internal error "Unauthorized".

## To Reproduce
just send message via directline

## Expected behavior
When I type "hi", I am expecting that proper feedback message return:
![image](https://user-images.githubusercontent.com/37282473/50869196-f596fa00-13ed-11e9-9a6a-c7c9542ac19f.png)

## Screenshots
![image](https://user-images.githubusercontent.com/37282473/50869579-9cc86100-13ef-11e9-9b4e-5dc66fc45d07.png)

After using ngrok.exe, it shows me that following information:
{
    "message": "An error has occurred.",
    "exceptionMessage": "Unauthorized",
    "exceptionType": "Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException",
    "stackTrace": "   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<GetTokenAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<ProcessHttpRequestAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at RIB.Visual.McTwo.BotService.Controllers.MessagesController.<Post>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()",
    "innerException": {
        "message": "An error has occurred.",
        "exceptionMessage": "响应状态代码不指示成功: 401 (Unauthorized)。",
        "exceptionType": "System.Net.Http.HttpRequestException",
        "stackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()"
    }
}

## Additional context
I doubt that bot configuration has issues. Can anyone help me how to config bot services.

[bug]
[dotnet]

**Comment by tdurnford** [comment]
It looks like you are using the wrong endpoint to send messages to your bot through DirectLine.

To send messages to your bot with DirectLine, you first need to use your DirectLine Secret to generate a token and a conversation Id which can be used to access a single conversation. Issuing a POST request to `https://directline.botframework.com/v3/directline/tokens/generate` should respond with a valid token along with the conversationId.

Then you can use the token and conversationId to message your bot by sending POST requests to `https://directline.botframework.com/v3/directline/conversations/{conversationId}/activities` with the activity in the body of the request. The request should then respond with the activityId.

For more information and detail on sending messages with DirectLine, please refer to the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0).

Let me know if this solves your issue. Hope this helps!

**Comment by rib-pet** [comment]
@tdurnford , thank you very much.

I am pretty sure that I am using correct endpoint and right directline secrete . in my local machine, "" is my endpoint, after I use ngrok.exe to generate https url. See my picture:

![image](https://user-images.githubusercontent.com/37282473/50952589-cd8dc080-14eb-11e9-9b39-3001a655dd78.png)

At Azure, I also put this endpoint for my bot service as below:
![image](https://user-images.githubusercontent.com/37282473/50952653-0af24e00-14ec-11e9-8be6-15199f39690c.png)

After above configuration, I call http request (directline) to my bot server. it turns out [500 internal error, unauthorized]. 

Any suggestions from your side?

**Comment by tdurnford** [comment]
This seems to be related to this issue https://github.com/Microsoft/BotBuilder/issues/4445

**Comment by tdurnford** [comment]
How are you requesting your authorization token?  If you are getting your token through DirectLine, all of your requests need to be through DirectLine. However, you can get an authorization token through the REST API which I believe should work with your approach. I would recommend taking a looking at the [Create a bot with the Bot Connector service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0) documentation.

**Comment by rib-pet** [comment]
@tdurnford , thx.

that approach you mentioned is for clarify Token_access right? In my opinion, directlien secret is band with current bot service. it should not have such "unauthorized" issue. Anyway, I will try. maybe it tells that why is like that.

**Comment by rib-pet** [comment]
it seems that ngrok is not working. I created another bot service, it's working
