### ISSUE TITLE
I am wondering whether I can save some data into BotDataStorage before user send the first message to bot

### ISSUE THREAD

**Issue by skyline9002** [Microsoft/BotBuilder-V3#107]
### SDK Platform
.Net BotBuilder 3.12.24

### URL of Code Sample
No

### Problem Description
I am wondering whether I can save some data into BotDataStorage before user send the initial message to bot.

what I have done and know:

1. Enable the default BlobTable implementation to manage state data.

2. Bot send proactive message to user and save some user-specific data by using StateClient.
    At this point, I know the bot framework actually did not save anything to BlobTable, I checked the 
    BlobTable there was no ConversationId I create at proactive message. 
   
    However I still can retrieve the data then I think at this point still using the memory to cache the 
    BotData, I also knew in conversation object there has a ExpireIn property, I can imaging the data will 
    be lost if user did not reply within certain amount of time. Also I want to know if I save as UserData 
    whether it will be expired also. 

3.  If user reply the message, then the BotData will be shown in the BlobTable.

So I want to know why the first proactive message will not persistent the data into BlobTable.

Thanks

**Comment by EricDahlvang** [comment]
@skyline9002  It looks like you had originally opened this in another repository almost a year ago, but it was moved here a few days ago.  I apologize that you did not receive an answer in the BotBuilder-Samples repository. **Is this still an issue for you?**

1. by BlobTable, are you referring to https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/TableBotDataStore.cs#L62 ?

2. StateClient uses the deprecated default Bot Builder storage, and not the configured BotBuilder-Azure storage.  

I'm not aware of the conversation object's ExpireIn property.  Token's expire, but the data in bot storage has no particular expiration.

---

The answer here: https://stackoverflow.com/questions/48327229/how-to-store-retrieve-bot-data-in-azure-table-storage-with-directline-channel/48713914#48713914  demonstrates how to store information in UserData before the user connects to the bot.  This also requires using that userid for the WebChat control.  (note: the bot in this example is in Node.js, but the page hosting the WebChat is .net)
