### ISSUE TITLE
Implementing Silent AAD Authentication in Bots

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder-V3#11]
Hello
Can we implement something like below in bot framework. 
https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-silent-AAD.md

Currently the user has to launch a window to authenticate. But if above works then if user is alreeady connected to some Azure AD then it can pick up auth tokent automatically. Please let me know.

**Comment by v-kydela** [comment]
Closing and directing traffic to StackOverflow: https://stackoverflow.com/questions/52811945/implementing-silent-aad-authentication-in-bots
