### ISSUE TITLE
[.NET SDK] 401 Unauthorized in 3.15.2.2 when posting back to user

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder-V3#120]
## Version

C# 3.15.2.2

## Describe the bug

The First user after long inactivity of bot suffers from not getting back any reply from the bot.
We were able to find the following from the logs.

directline.botframework.com | HTTP | POST /v3/conversations/(ID goes here)/activities/(ID goes here) | https://directline.botframework.com/v3/conversations/(ID goes here)/activities/(ID goes here) | FALSE | 401 | 434 | 250ms-500ms

## To Reproduce
1. Let the bot sleep for a long time and awake it using web chat.

## Expected behavior
The bot should be giving the reply as for every other user.

## Additional context
This issue was happening with azure hosted instance.

[The same was being discussed in the following issue post but no resolution provided there.](https://github.com/Microsoft/BotBuilder/issues/4733)

**Comment by jwiley84** [comment]
Hi @alokraj68! 

Can you update to 3.19 or higher and let me know if this is still happening?

**Comment by CoHealer** [comment]
@alokraj68, have you had the chance to try the recommendation @jwiley84 made?

**Comment by RajneeshVerma** [comment]
@jwiley84 n @CoHealer, 
Thanks for update, we have updated to 3.20.1 and deployed, but we need some more time to confirm as its not frequent.

Hopefully will have update on next week :)

**Comment by CoHealer** [comment]
Hi @RajneeshVerma, checking in to see if there's an update. Any news?

**Comment by alokraj68** [comment]
We did not get that issue after that till now. we are still going through testing. Will reopen the ticket if we receive it again.
