### ISSUE TITLE
In skype group chat, IMessageActivity.GetMentions() only contains the first mention

### ISSUE THREAD

**Issue by tgckpg** [Microsoft/BotBuilder-V3#122]
## Version
3.20.1

## Describe the bug
When mentioning others using "@". message. Entities only contains first mention.

## To Reproduce
Use this sample code
```csharp
IMessageActivity message = await argument;

string DebugMesg =
	$"\nFrom.Id: {context.Activity.From.Id}" +
	$"\nRcpt.Id: {context.Activity.Recipient.Id}" +
	"\n==== MESG ====\n" + WebUtility.UrlEncode( message.Text.Substring( 5 ) ) + "\n==== END MESG ====";

foreach ( Entity e in message.Entities )
{
	DebugMesg += $"\nEntity: {e.Properties.ToString()}";
	break;
}

await Response( context, DebugMesg );
context.Wait( MessageReceivedAsync );
```
1. Use the Skype UWP on Win 10
2. In group chat, mention the bot with some other contacts

## Expected behavior
GetMentions() Should contain all the mentions. i.e. multiple `Entity` in `message.Entities`.

[bug]
[dotnet]

**Comment by EricDahlvang** [comment]
I just tested this with:
![image](https://user-images.githubusercontent.com/11055362/54040938-62730a00-417b-11e9-86ee-fe11ed17be36.png)

Multiple @Mentions are returned from GetMentions(), as well as within message.Entities. Please try the code you've shared without the `break;` inside the foreach (I also had to replace all > and < characters):

```cs
var mentions = message.GetMentions();
string DebugMesg =
                    $"\nFrom.Id: {context.Activity.From.Id}" +
                    $"\nRcpt.Id: {context.Activity.Recipient.Id}" +
                    "\n==== MESG ====\n" + System.Net.WebUtility.UrlEncode(message.Text.Substring(5)) + "\n==== END MESG ====";

foreach (Entity e in message.Entities)
{
     DebugMesg += $"\nEntity: {e.Properties.ToString()}";
     //break;
}
DebugMesg = DebugMesg.Replace('<', '-').Replace('>', '-');
await context.PostAsync(DebugMesg);
```

**Comment by tgckpg** [comment]
Ah, I'm really sorry...must've been blind. That was a stupid mistake. 

This is completely my bad. Thank you!

**Comment by EricDahlvang** [comment]
You're welcome.  I'm glad it was something minor.  

Happy coding!  :)
