### ISSUE TITLE
the wrong locale happened when change the language

### ISSUE THREAD

**Issue by FengXiaohe** [Microsoft/BotBuilder-V3#125]
## Version
3.20.1.42
C#

## Describe the bug
I have build two Facebook page for the chat bot which is build by botframework, and the one page is talk in English, the other is Japanese. It is ok if I just talk with one page. But after finish the talk in Japanese page, if I start talk with the English page, the text is fine in English but the option(Such as the Dialog.Choice's option or the HeroCard's CardAction) will be in Japanese.

## To Reproduce
1. Build on app In Facebook
2. Build two Facebook to connect to the Facebook App, one is for English chatbot, and another is for Japanese.
3. Connect this Facebook app to botframework's Facebook channel
4. In the MessageController.cs, before invoke the Dialog, Set the Activity.Locale according to the Facebook page.
5. In the botframework Dialog, all the text is set to be read from resource file.
6. Talking with the Japanese Page.
7. Talking with the English Page. Then the message which has been returned from chat bot will be mixed with English and Japanese. Such as following screenshot.

## Expected behavior
The message's language which has been returned from chat bot should be due to Facebook's page.

## Screenshots

![image](https://user-images.githubusercontent.com/30440909/54817411-d233d980-4cd1-11e9-939e-8ddda9c73662.png)

## Additional context

[bug]
[dotnet]

**Comment by FengXiaohe** [comment]
I found the reason. But it is still botframework's bug, I think.

When I change the talking chat bot from one Facebook page A to another page B, page B's StartAsync method must be revoked. Actually in my programming some values are initiated by the resource file in the StartAsync method. But this StartAsync method's locale is previous Facebook page's locale. So I have to initiate my values in the next method which is the parameter in the Context.wait in StartAsync.

**Comment by EricDahlvang** [comment]
Can you share the code?

**Comment by FengXiaohe** [comment]
The code is like this.

```C#
        private void InitialValues()
        {
                HelloOptions.Pairs.Clear();
                HelloOptions.Pairs.Add(new KeyValuePair<string, string>("1", LanguageResource.Aboutproduct));
                HelloOptions.Pairs.Add(new KeyValuePair<string, string>("2", LanguageResource.Testdrive2));
        }

        public async Task StartAsync(IDialogContext context)
        {
            InitialValues();
            
            // check the values of HelloOptions
            Trace.TraceInformation(JObject.FromObject(HelloOptions.Pairs).ToString());

            // Show the list of plan  
            context.Wait(ShowWelcomeMsg);
        }

        public async Task ShowWelcomeMsg(IDialogContext context, IAwaitable<IActivity> argument)
        {

            var activity = await argument;

            await SendWelcomeMessage(context);

            context.Wait(ChoiceReceivedAsync);
        }
```

I checked the values of  HelloOptions.Pairs in StartAsync. When I change from one Facebook Page A to Page B, the HelloOptions.Pairs's locale seem to be following the Page A. After I move the [InitialValues();
] into the method of ShowWelcomeMsg, the locale turn to be correct.

**Comment by EricDahlvang** [comment]
@FengXiaohe Is HelloOptions a dialog field, or is it a static field?  Please share the rest of the Dialog code. There is not enough here to determine what the issue is exactly, but it looks like HelloOptions is shared between users or conversations.

**Comment by FengXiaohe** [comment]
I'm sorry for that. I checked that. The HelloOptions is defined like this.

```C#
        public class HelloOptions : Dictionary<string, string>
        {
            public static IDictionary<string, string> Pairs = new Dictionary<string, string>();
        }
```

As it is defined as static, it must be shared, right ? I'm sorry for my bad code.

**Comment by EricDahlvang** [comment]
@FengXiaohe Don't feel bad.  I've written a lot of bad code myself.... I try to look at it as part of the learning process.

I'm glad you've solved this issue.  

Happy coding! :)
