### ISSUE TITLE
FormDialog static error using Json

### ISSUE THREAD

**Issue by Skaaapi** [Microsoft/BotBuilder-V3#126]
## Version
3.20.1.42

## Describe the bug
When using multiple dialogs, if one of them has an error, all other won't work anymore.

## To Reproduce
Dialogs are called as following : 
`dialogForm = new FormDialog<JObject>(new JObject(), MakeJsonForm, FormOptions.PromptInStart, luisResult.Entities);
context.Call<JObject>(dialogForm, DialogFormComplete);`

My BuildJson function : 
`public static IForm<JObject> BuildJsonForm()
        {
            return new FormBuilderJson(JObject.Parse(structure.Schema)).Build();
        }`

And sample Json to test : 
Train (working) : 
`string json = @"{  
               ""References"":[  
                  ""Exabot.dll""
               ],
               ""Imports"":[],
               ""type"":""object"",
               ""required"":[],
               ""properties"":{  
                  ""Departure"":{  
                     ""type"":[  
                        ""string"",
                        ""null""
                     ]
                  }
               },
               ""OnCompletion"":""await context.PostAsync(\""Votre réservation est prête.\"");""
            }";`

Pizza (Not working) : 
`string json = @"{  
               ""References"":[  
                  ""Exabot.dll""
               ],
               ""Imports"":[],
               ""type"":""object"",
               ""required"":[],
               ""properties"":{  
                  ""Pizza"":{  
                     ""type"":[  
                        ""string"",
                        ""null""
                     ],
		             ""Next"": ""if(value == \""Pizza with ' quote\"") {return NextStep(new [] {nameof(Time)});} else {return NextStep();};""
                  }
                },
               ""OnCompletion"":""await context.PostAsync(\""Votre réservation est prête.\"");""
            }";`

I added willingly an error in the BuildJsonPizzaForm schema, in the "Next" value.
One form works fine (train), and one other don't work (pizza).

- If I say "Train", that'll work fine
- If I say "Pizza", an error will be occured (we wanted to)

But if I say Train again, that won't work anymore, and will still catch the "Pizza" error.

## Expected behavior
Even if a form cannot be built, I would like to be able to still be using other forms.

## Screenshots
Train is working fine till I'm calling Pizza form. Train won't work anymore then : 
![image](https://user-images.githubusercontent.com/42973489/54912905-ec4c0280-4ef1-11e9-9a8c-dabf818ada7a.png)

If both json schema are valid, all is working good.

Is this a known bug ? (Didn't get anything on the web).

Thanks in advance :).

[bug]
[dotnet]

**Comment by EricDahlvang** [comment]
Hi @Skaaapi 

This was previously reported here: https://github.com/Microsoft/BotBuilder/issues/4755  and a fix was submitted: https://github.com/Matti-Koopa/BotBuilder/commit/426bc89e0f268d45416aa8ce27110ad3c5692045  However, that fix caused out of memory issues and had to be rolled back: https://github.com/Microsoft/BotBuilder-V3/pull/76

It seems a better fix would be to catch the runtime compilation exception, and clear the scripts at that point.  Something like:

```cs
    try
    {
        var script = CSharpScript.Create<R>(code, _options, typeof(G));
        return script.CreateDelegate();
    }
    catch (Microsoft.CodeAnalysis.Scripting.CompilationErrorException ex)
    {
            lock (_scripts)
            {
                _scripts.Clear();
            }
        throw;
    }
```

Would you like to submit a PR to fix this?  This has not been a high priority, since this issue only occurs if there is a bug in the .json for a form.

**Comment by Skaaapi** [comment]
Thanks for your nice answer, I fixed it adding those lines. I replaced the dll with the edited one. That should be fine for the moment, we'll migrate to the V4 Framework soon ^^.

Thanks again, have a nice day !
