### ISSUE TITLE
Bot state seems to be messed up. Dialog not working as expected

### ISSUE THREAD

**Issue by sagnikm95** [Microsoft/BotBuilder-V3#127]
I am using SDK V3 version 3.15.3. In my bot I am simulating a conversation flow using Dialogs. But instead of hitting the call back function mentioned in context.wait(), after hitting Message.Controller the control is going to StartAsync function in my root dialog and as a result the whole dialog flow is restarting from the beginning rather than proceeding to the function mentioned in the callback for context.wait(). This behavior is also quite random as in few cases ( specially when debugging locally) the bot is acting as expected.

**Comment by EricDahlvang** [comment]
Please share the code, so we can better assist you.

**Comment by sagnikm95** [comment]
Hi. Thanks for getting back. my bot was getting reinitialised (startAsync function was getting called) in between dialog flow. i was using in memory data store. Since it has a limit of 64kb i am assuming some sort of overflow was resulting in the bot state getting reinitialised. Any ways after changing the state storage type to blob table the issue has not come up. You can close this. If it occurs again I will reopen te issue with code snippet.
