### ISSUE TITLE
Incorrect conversation creation parameters

### ISSUE THREAD

**Issue by qiu999** [Microsoft/BotBuilder-V3#128]
when i user the /v3/conversations api to test 1:1 chat by using this json:
`{
    "topicName": "Topic Creation Test",
    "members": [
        {
            "id": "29:1NFWRrUtLwbhIIwTEu_wrlFu8aJC0XbyHu4xsav1EpLNqXpOtcUa3ceJ5aD0cSNCVoWKcTqqmJPoNGMYXYLH1VQ"
        }
    ],
    "bot": {
        "id": "f1bb17ff-10c9-464e-9b30-261c92a37868"
    },
    "channelData": {
        "tenant": {
            "id": "a71f8b55-c358-465a-a300-36f0f9d15726"
        }
    },
    "isGroup": false,
    "activity": {
        "text": "Hello, world!",
        "type": "message"
    }
}`
it works,but i want to create a group chat ,so i change the param 'isGroup' as true, it occurs an error: `{
    "error": {
        "code": "BadSyntax",
        "message": "Incorrect conversation creation parameters"
    }
}`
i am not sure which parameters is need ,i searched this link [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation) also not sure which parameters is need ,anybody can help me?

**Comment by v-kydela** [comment]
@qiu999 - What channel are you using? Is it Microsoft Teams?

**Comment by qiu999** [comment]
@v-kydela yes, i am working on MS Teams integration, i want to create a group chat in customer's chat like this:
![image](https://user-images.githubusercontent.com/17703508/55526227-be6f7680-56c6-11e9-998b-9148a93478a4.png)

**Comment by v-kydela** [comment]
There are two problems here that I can see. For one thing, you're trying to start a group conversation with only one person. For another thing, you're trying to start a group conversation with a bot. Bots cannot be added to group conversations in Teams. In order to chat with a bot in a group, you have to add the bot's app to a team and tag the bot in a team channel. Is that what you want to do?

**Comment by qiu999** [comment]
hi @v-kydela , thanks for your answer, do you mean i can create a channel ? When creating a teams channel means the whole teams members can receive the bot message.  I want to create a private group chat that cannot disturb other people who are  not in this private group,can you give some suggest for me ?

**Comment by v-kydela** [comment]
I think you best option would be to create a new team, though that would require an admin. I will ask around and see if I can get any more information.

**Comment by v-kydela** [comment]
@qiu999 - It turns out bots will be able to connect to private group chats soon, and the feature is already in developer preview.

**Comment by v-kydela** [comment]
@qiu999 - The public developer preview can be accessed here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features

Thank you for the question. If it's all right with you, I will close this issue now.

**Comment by ShubhaKV** [comment]
Hi,

Currently can we send adaptive card to particular group in teams??
