### ISSUE TITLE
Not working in Azure Government 

### ISSUE THREAD

**Issue by fgarofalo56** [microsoft/BotBuilder-V3#130]
V3 SDK does not work in Azure Government (MAG).  The bot authentication fails, as it looks like bit connector uses the commerical endpoints to handle bot authentication and there is not a way to override the endpoints, to point to Azure Government.

**Comment by fgarofalo56** [comment]
Any update on this?  I am referring to the auth between the bot and the bot connector.  With the SDK for V3 it points only to the commercial endpoints, and fails to auth the bot to the connector server.  Is there a way to make this work with OpenID that is refranced here:
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0

**Comment by EricDahlvang** [comment]
Hi @fgarofalo56 

More information on Azure Bot Service in Azure Government can be found here: https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-services-aiandcognitiveservices#azure-bot-service

I believe Bot Builder V3 SDK does support it. The authentication tenant can be supplied by adding a ChannelAuthTenant app setting.  Support for this was added with this commit: https://github.com/Microsoft/BotBuilder-V3/commit/58a69ab3bbf85687d8ddc23af8623babef6cb971#diff-f9dafa7c10b389d6aaf7bace09d99c89

Which version of the v3 sdk are you using?

**Comment by fgarofalo56** [comment]
I am using v3 sdk: 3.20.1
Is there any documentation on how to point it to Gov endpoint?  Do we need to replace   [BotAuthentication] with somthing in MessagesController.cs?  Any help you can provide would be great.

**Comment by EricDahlvang** [comment]
The V3 sdk does not support Azure Gov.

We recommend new bots use the V4 sdk.  I haven't yet been able to find clear instructions on how to configure it.  I'll let you know.

**Comment by EricDahlvang** [comment]
For v4, in C#, use `ConfigurationChannelProvider`. Pass it into the constructor of `BotFrameworkHttpAdapter`. It reads the `ChannelService `setting from appsettings. For JS, set the `channelService `property of `BotFrameworkAdapterSettings `when creating a `BotFrameworkAdapter`.

`ChannelService` app setting should be `https://botframework.azure.us`

Due to the limited lifetime of the Bot Builder V3 sdk, there are no plans to support v3 bots in Azure Gov.
