### ISSUE TITLE
Docs reference link is broken

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder-V3#135]
The reference link on this page 
`https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-3.0`
![image](https://user-images.githubusercontent.com/1172479/56608988-6dc2ad80-65e2-11e9-814c-200d8199b73b.png)

instead of loading
`https://docs.botframework.com/en-us/node/builder/chat-reference/modules/_botbuilder_d_.html`

gets redirected to: 
`https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0`

**Comment by EricDahlvang** [comment]
docs.botframework.com has been taken down and documentation moved to docs.microsoft.com.  The api browser will replace the former docs you've referenced: https://docs.microsoft.com/en-us/javascript/api/?view=botbuilder-ts-latest  The TypeScript v3 are not there yet, but the team is working on them.

**Comment by EricDahlvang** [comment]
This link has been fixed, and now points to https://aka.ms/bot-jssdk-v3

Thank you for reporting this.
