### ISSUE TITLE
I have an Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by pavigor** [microsoft/BotBuilder-V3#136]
## Versions
What package version of the SDK are you using.
**botbuilder@3.16.0**
What nodejs version are you using
**v8.16.0**

## Describe the bug
Some time ago I started to get error when my bot receives the command from user:

> `Error: Hostname/IP doesn't match certificate's altnames: "Host: state.botframework.com. is not in the cert's altnames: DNS:*.azurewebsites.net, DNS:*.scm.azurewebsites.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net, DNS:*.sso.azurewebsites.net"
>     at Object.checkServerIdentity (tls.js:223:17)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1122:29)
>     at emitNone (events.js:106:13)
>     at TLSSocket.emit (events.js:208:7)
>     at TLSSocket._finishInit (_tls_wrap.js:643:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
> `

## To Reproduce
The error may encounter from time to time

## Expected behavior
Not sure

[bug]

**Comment by EricDahlvang** [comment]
@pavigor is this still an issue for you?

**Comment by pavigor** [comment]
> @pavigor is this still an issue for you?

Hi, there is no issue in last two weeks. Can't reproduce. I will try to rewrite my bot with new API.

**Comment by OksanaBerdnik** [comment]
I've received this error: Error: Hostname/IP doesn't match certificate's altnames: "Host: facebook.botframework.com. is not in the cert's altnames: DNS:*.azurewebsites.net, DNS:*.scm.azurewebsites.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net, DNS:*.sso.azurewebsites.net"
    at Object.checkServerIdentity (tls.js:223:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1111:29)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
Any suggestions would be greatly appreciated
