### ISSUE TITLE
Bot throwing error Value cannot be null. Parameter name: clientId

### ISSUE THREAD

**Issue by tinuCoder** [microsoft/BotBuilder-V3#140]
## Bot throwing error Value cannot be null. Parameter name: clientId

I am using Bot framework v3.20 for my application
my Bot code sample is as below.

```cs
private async Task HandleSystemMessage(Activity activity)
        {
            try
            {
                switch (activity.Type)
                {
                    case ActivityTypes.DeleteUserData:
                    case ActivityTypes.ConversationUpdate:
                        #region Welcome message for conversationUpdate
                        MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl, DateTime.MaxValue);
                        ConnectorClient connectorTeams = new ConnectorClient(new Uri(activity.ServiceUrl));
                        Activity welcomeMessageTeams = activity.CreateReply();
                        welcomeMessageTeams.Type = "message";
                        var iConversationUpdate = activity.AsConversationUpdateActivity();
                        if (activity.Type == ActivityTypes.ConversationUpdate)
                        {
                            welcomeMessageTeams.Text = $"Hi " + activity.From.Name + ", I am Matoo, your friendly, intelligent advisor!";
                            foreach (var member in iConversationUpdate.MembersAdded)
                            {
                                if (member.Id == iConversationUpdate.Recipient.Id)
                                {
                                    await connectorTeams.Conversations.ReplyToActivityAsync(welcomeMessageTeams);
                                }
                            }
                        }
                        #endregion
                        break;
                    case ActivityTypes.Typing:
                    case ActivityTypes.ContactRelationUpdate:
                        break;
                    case ActivityTypes.Event:
                        break;
                }
            }
            catch (Exception ex)
            {
            }
        }
```
When the bot tries to send response to the user from line "await connectorTeams.Conversations.ReplyToActivityAsync(welcomeMessageTeams);"
it throws an exception 
Bot throwing error Value cannot be null. Parameter name: clientId

Unable to understand the issue.
Please help

**Comment by EricDahlvang** [comment]
Hi @tinuCoder 

The only time I've seen `Value cannot be null. Parameter name: clientId` is while communicating with a bot that does not have a MicrosoftAppId and MicrosoftAppPassword in the web.config  Are these values present in your Web.config file?

**Comment by tinuCoder** [comment]
Hi @EricDahlvang Yes I had correct MicrosoftAppId and MicrosoftAppPassword in the web.config files.

Seems i have found the solution for this. The AzureWebJobsStorage value was was somehow empty, in the configuration settings. I created a storage about and added the connection string in the configuration settings. Now its working fine.

![image](https://user-images.githubusercontent.com/25457761/57683902-b6034780-7645-11e9-8a5f-49eee43a5ea7.png)

We can close this issue if no more actions are needed.
