### ISSUE TITLE
MethodNotAllowed with Microsoft.Bot.Connector.BotState.<GetConversationDataWithHttpMessagesAsync>

### ISSUE THREAD

**Issue by rib-pet** [microsoft/BotBuilder-V3#141]
## Version
What package version of the SDK are you using.
3.20.1.42

## Describe the bug
Give a clear and concise description of what the bug is.
try to use emulator and ngrok to debug local source code. it can be working fine.
Once deploy into Azure. it always prompts me "MethodNotAllowed" error

## Expected behavior
Give a clear and concise description of what you expected to happen.
This is exception can not be there.
**I am using "MultiCredentialProvider" to deal with multiple botAPPID and appPassword.**
`   public class MultiCredentialProvider : ICredentialProvider
	{
		public Dictionary<string, string> Credentials = new Dictionary<string, string>();

		public List<string> ApptokenList = new List<string>() { Consts.Ytwo, Consts.RibBotReg, Consts.TwoWorld, Consts.MctwoDe };
		/// <summary>
		/// 
		/// </summary>
		public MultiCredentialProvider()
		{
			if (ApptokenList.Count >= 0)
			{
				foreach (var tok in ApptokenList)
				{
					Credentials.Add(WebConfigurationManager.AppSettings.Get(Consts.MicrosoftAppId + "-" + tok), WebConfigurationManager.AppSettings.Get(Consts.MicrosoftAppPassword + "-" + tok));
				}
			}
		}

		public Task<bool> IsValidAppIdAsync(string appId)
		{
			return Task.FromResult(Credentials.ContainsKey(appId));
		}

		public Task<string> GetAppPasswordAsync(string appId)
		{
			return Task.FromResult(Credentials.ContainsKey(appId) ? Credentials[appId] : null);
		}

		public Task<bool> IsAuthenticationDisabledAsync()
		{
			return Task.FromResult(!Credentials.Any());
		}
	}

	[BotAuthentication(CredentialProviderType = typeof(MultiCredentialProvider))]
	public class MessagesController : ApiController`

Here are my Post method :
`[ResponseType(typeof(void))]
		public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
		{
			if (activity.Type == ActivityTypes.Message)
			{
				DateTime start = DateTime.Now;
				if (!string.IsNullOrEmpty(activity.Text) || activity.Value != null)
				{
					try
					{
						Util.SetThreadCultureInfo(activity);

						var luisServices = Util.GetRuntimeLuisServices(activity);
						await Conversation.SendAsync(activity, () => new MctwoLuisDlg(luisServices));
					}
					catch (Exception e) 
					{
						var error = e.ToString();
						Trace.TraceError(error);
						var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
						{
							var reply = activity.CreateReply(error + "/r/n" + e.StackTrace);
							await connector.Conversations.ReplyToActivityAsync(reply);
						}
					}
				}
		}
}`
here are my Global.asax.cs :
`	public class WebApiApplication : HttpApplication
	{
		/// <summary>
		/// 
		/// </summary>
		CancellationTokenSource _getTokenAsyncCancellation = new CancellationTokenSource();

		/// <summary>
		/// 
		/// </summary>
		protected void Application_Start()
		{

			Task.Factory.StartNew(async () =>
			{
				while (!_getTokenAsyncCancellation.IsCancellationRequested)
				{
					foreach (var botCreds in new MultiCredentialProvider().Credentials)
					{
						var credentials = new MicrosoftAppCredentials(botCreds.Key, botCreds.Value);
						try
						{
							var token = await credentials.GetTokenAsync(true).ConfigureAwait(false);
						}
						catch (Exception ex)
						{
							//log error
							Trace.TraceError(ex.Message);
						}
					}
					await Task.Delay(TimeSpan.FromSeconds(30), _getTokenAsyncCancellation.Token).ConfigureAwait(false);
				}
			}).ConfigureAwait(false);

			//var store = new InMemoryDataStore();

			Conversation.UpdateContainer(
			builder =>
			{
				/*
				 memory storage
				 builder.Register(c => store)
                         .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                         .AsSelf()
                         .SingleInstance();

               builder.Register(c => new CachingBotDataStore(store,
                          CachingBotDataStoreConsistencyPolicy
                          .ETagBasedConsistency))
                          .As<IBotDataStore<BotData>>()
                          .AsSelf()
                          .InstancePerLifetimeScope();

				 */

				//https://github.com/microsoft/BotBuilder-V3/issues/5
				// https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/
				// Azure Table Storage
				builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));
				var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
				builder.Register(c => store)
					.Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
					.AsSelf()
					.SingleInstance();

				/*
				 handle concurrecy issue 
				 https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0
				 */
				builder.Register(c => new CachingBotDataStore(store,
					CachingBotDataStoreConsistencyPolicy.ETagBasedConsistency))
					.As<IBotDataStore<BotData>>()
					.AsSelf()
					.SingleInstance();

				//builder.RegisterModule(new ReflectionSurrogateModule());

				// Scorable dialog
				builder.RegisterModule<GlobalMessageHandlersBotModule>();
			});
			GlobalConfiguration.Configure(WebApiConfig.Register);

		}

		/// <summary>
		/// 
		/// </summary>
		protected void Application_End()
		{
			_getTokenAsyncCancellation.Cancel();
		}
	}`

[bug]
[dotnet]

**Comment by rib-pet** [comment]
@EricDahlvang , follow your request, I upload my source code.
![image](https://user-images.githubusercontent.com/37282473/57741787-f66bcf80-76f0-11e9-9c1c-0ec5a2f08eba.png)

![image](https://user-images.githubusercontent.com/37282473/57741821-13080780-76f1-11e9-87e8-9aa1ac23a104.png)

**Comment by rib-pet** [comment]
Just comment out in constructor method of class MessageController.

`static MessagesController()
		{

			// Update the container to use the right MicorosftAppCredentials based on
			// Identity set by BotAuthentication
			//Conversation.UpdateContainer(builder =>
			//{
			//	builder.RegisterModule<GlobalMessageHandlersBotModule>();

			//	builder.Register(c => ((ClaimsIdentity)HttpContext.Current.User.Identity).GetCredentialsFromClaims())
			//		.AsSelf()
			//		.InstancePerLifetimeScope();
			//});
		}
`
GetCredentialsFromClaims seems will automatically call botstates api
![image](https://user-images.githubusercontent.com/37282473/57759761-3a7cc580-772d-11e9-90ef-9c079785cf36.png)

Therefore, I close this issue, Thank your Eric

**Comment by EricDahlvang** [comment]
Yes, Conversation.UpdateContainer should only be called once. During app startup. If it is called again, it will overwrite the previous autofac registrations.
