### ISSUE TITLE
No error given for a 403 response

### ISSUE THREAD

**Issue by oneeman** [microsoft/BotBuilder-V3#142]
## Version
3.15.0

## Describe the bug
If you attempt to post a conversation to a team after the bot has been removed, the server gives a 403 error, bot the botbuilder method authenticatedRequest returns a non-error rather than an error.

## To Reproduce
1. Install a bot on a team
2. Remove the bot from the team
3. Attempt to create a conversation in one of the team's channels using that bot
4. Server replies with a 403

## Expected behavior
The error callback would be triggered

## Additional context
The code in question can be seen at https://github.com/microsoft/BotBuilder-V3/blob/master/Node/core/src/bots/ChatConnector.ts#L844-L866 .  For status codes of 400 except 401 or 403, it triggers an error (line 859).  However, for 401 and 403 there is special handling, where it tries to refresh the token if it hasn't already been refreshed.  However, if it has been refreshed, the else clause is hit and lines 851 is executed:
```
callback(null, response, body);
```

This doesn't make sense, because what we got from the server is an error, and the callback is being called with null for the error, and with the body.  Instead, it should be
```
var txt = options.method + " to '" + options.url + "' failed: [" + response.statusCode + "] " + response.statusMessage;
callback(new Error(txt), response, null);
```
as is done for other codes over 400.

[bug]
[javascript]

**Comment by EricDahlvang** [comment]
Hi @oneeman 

Please share the code you are using to 

> Attempt to create a conversation in one of the team's channels using that bot

**Comment by jspruance** [comment]
I was able to repo the issue. Created a pull request with proposed fix.

**Comment by oneeman** [comment]
@EricDahlvang I can't share our code.  But I can say that we are using the authenticatedRequest method directly, because we needed to get back both the activity id and the thread id of the newly-created conversation (so that we can later proactively post replies to it), and the other methods, such as startConversation, give us back only the activity id, not the thread id.

However, the other methods use authenticatedRequest, and don't have special handling for 403 errors, so the problem I identified also affects callers who use authenticatedRequest indirectly through methods such as startConversation.  For example, from looking at the code, if you use startConversation, it will hit this line: https://github.com/microsoft/BotBuilder-V3/blob/master/Node/core/src/bots/ChatConnector.ts#L352 , and you will get an uninformative error "Failed to start conversation: no conversation ID returned", rather than the 403, and so the caller will not be able to tell that the problem was that the bot has been uninstalled.  This contrasts with other errors (e.g. 500, 502, etc.) where the error is returned from authenticatedRequest and then bubbled up to the user, and does not seem correct.

@jspruance Thank you for the PR!

**Comment by EricDahlvang** [comment]
@oneeman Thank you for the detailed description.  Considering that Jonathan was able to repro, and provided a fix, sharing the code is no longer needed.

Thank you for reporting this.

**Comment by EricDahlvang** [comment]
This will go out in the next release.  

Closing, since the PR has been merged.
