### ISSUE TITLE
Proactive request to URL Button URL value

### ISSUE THREAD

**Issue by Zhashkha** [microsoft/BotBuilder-V3#159]
## Version
3.16.0

## Describe the bug
Hi guys, 

I'm just creating a hero card with URL Button. Facebook Messenger sends request to the button's URL automatically and it ruins my algorithm, because after initial request modifications in database are done.

## Expected behavior
No automatic request to URL button's URL value

**Comment by Zhashkha** [comment]
I'm expecting that Facebook Messenger won't send request to URL Button's URL value by default. Thanks for reply.

**Comment by EricDahlvang** [comment]
Hi @Zhashkha

Please share the code you for the card and button.  I am not aware of the behavior you've described. I would like to try repeating the issue.

**Comment by Zhashkha** [comment]
Hi Eric

Thank you for your answer. It's just a simple URL button code. After you posting this card, Messenger goes to this URL automatically without any intention from your side.

//IMessageActivity replyToConversation


replyToConversation.Attachments = new List<Attachment>();
ThumbnailCard card = new ThumbnailCard();

// set buttons
string redirectionUrl = BotticelliApplicationConsts.HostBaseUrlSecure + BotticelliApplicationConsts.HostRedirectUri + "?token=" + token;
List<CardAction> cardActions = new List<CardAction>();
cardActions.Add(new CardAction()
            {
                Type = ActionTypes.OpenUrl,
                Title = TemplateTexts.LinkRedirectionActionTitlePay,
                Value = redirectionUrl
            });

card.Buttons = cardActions;
card.Title = "title"; // set any title
card.Subtitle = "subtitle"; // set any subtitle
replyToConversation.Attachments.Add(card.ToAttachment());

**Comment by EricDahlvang** [comment]
Hi @Zhashkha 

I've tried to reproduce the issue, and I'm not seeing activity at the url until clicking on the button. 

```cs
                    reply.Attachments = new List<Attachment>();
                    ThumbnailCard card = new ThumbnailCard();

                    // set buttons
                    string redirectionUrl = "https://e2a9247b.ngrok.io/WebChat/Chat";
                    var cardActions = new List<CardAction>();
                    cardActions.Add(new CardAction()
                    {
                        Type = ActionTypes.OpenUrl,
                        Title = "Card Title",
                        Value = redirectionUrl
                    });

                    card.Buttons = cardActions;
                    card.Title = "title"; // set any title
                    card.Subtitle = "subtitle"; // set any subtitle
                    reply.Attachments.Add(card.ToAttachment());

                    await context.PostAsync(reply);
```

Are you also attaching an image to the ThumbnailCard?  Images will be retrieved, but as far as I know the ActionTypes.OpenUrl path will not be hit until a user clicks on the button.  

I do know that the Bot Framework will not call the url automatically, so however this is happening it must be on the Facebook Messenger side.  Have you opened an issue with Messenger support?

Are you experiencing this with the messenger application on desktop or mobile, or a specific browser?  Is there any other information you can provide which might enable me to reproduce this behavior?

**Comment by Zhashkha** [comment]
Hi Eric,

Thank you for your answer. Indeed it happens only with FB Messenger and I've opened an issue. If you want to reproduce this behavior, you have to use Messenger and it doesn't matter whether it is a mobile or desktop. Thanks !

**Comment by EricDahlvang** [comment]
I'm sorry @Zhashkha but I've been unable to repeat this with the code shared above, using Messenger.  I do not receive a call @/webchat/chat until I click the button.    Please let me know if you have some other code I can use to reproduce the issue.  For now, I'm closing this as not reproducible.
