### ISSUE TITLE
Link to BotBuilder example is not available anymore

### ISSUE THREAD

**Issue by bugb** [microsoft/BotBuilder-V3#166]
## Describe the bug
In the instruction file: https://github.com/Microsoft/BotBuilder-V3/tree/master/Node/examples#overview
```
git clone https://github.com/Microsoft/BotBuilder.git
```
should be:
```
git clone https://github.com/Microsoft/BotBuilder-V3.git
```

## To Reproduce
1. Clone repo: `git clone https://github.com/Microsoft/BotBuilder.git`
2. `cd BotBuilder`
3. There is no `Node` folder inside it:
![image](https://user-images.githubusercontent.com/9280412/67465007-8e8dbd80-f66e-11e9-9bdf-5468f967fc52.png)

## Expected behavior
The `Node` folder should be exist.

[bug]
[javascript]

**Comment by congysu** [comment]
@bugb can you please clone via this url: https://github.com/Microsoft/BotBuilder-V3.git  Thanks.
