### ISSUE TITLE
Question: Will bot services (written with NodeJS SDK v3.14, using DirectLine v3 APIs) stop working after Dec 31, 2019?

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotBuilder-V3#169]
We have bot services running in production and serving multiple customers. They are written with botbuilder NodeJS v3.14 and uses DirectLine v3 APIs.
We are hearing talks about Microsoft deprecating v3 bots after 31st Dec 2019.

Can you please clarify, after 31st Dec 2019
Will our already-running v3 bots stop working?
Will we be able to write new bots with v3 SDK, deploy and use them?

**Comment by dmvtech** [comment]
Yes @bhushanvadgave , already v3 bots will continue to run. Yes, you will be able to write new bots using existing v3 packages/samples/templates and deploy. You won't be able to create v3 bots in the portal.

https://blog.botframework.com/2019/06/07/v3-bot-broadcast-message/

- Migration Documentation: https://aka.ms/v3v4-bot-migration
- End of lifetime support announcement: https://aka.ms/bfmigfaq

@EricDahlvang Any other things to be aware of?

**Comment by bhushanvadgave** [comment]
Thank you so much @dmvtech
