### ISSUE TITLE
problem when try to call an another Rest-api at Botframework-V3+C#.net 

### ISSUE THREAD

**Issue by tutul2010** [microsoft/BotBuilder-V3#177]
Hi,
I stuck with a problem as..
When i was trying to call another Rest Api end point (rest-api done at dotnetcore 2.1) by Post-verb method at Botframework-V3+C#.net .
Problem is like as **debugger point(at Visual studio 2017 IDE) was not returning  to Botframework-V3 code after calling to api**.
The Rest-Api app (developed at dotnetcore 2.1) was done by our team and it is working file by Postman tool and also cors enable for access.
At Below ,Exception msgs are coming at Botframework-V3,C#.net code base
```
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at QnABot.Services.ApiServicesCall.<VmCreationApiServPostApi>d__3.MoveNext()
```
I am not using asyn-await at Api code
Please help.

Thanks,
Tutul

**Comment by EricDahlvang** [comment]
Hi @tutul2010 

Calling an api from the bot code should work the same in a bot as it would from any web application.  Have you tried creating a console app, or a separate program, that calls the api?  

If you share the calling code here, I can take a look and see if anything stands out.

**Comment by EricDahlvang** [comment]
Closing since: 
https://github.com/microsoft/BotFramework-Services/issues/172#issuecomment-576360336

![image](https://user-images.githubusercontent.com/11055362/73036606-e6b89500-3e00-11ea-9353-9825a1bb2f1d.png)
