### ISSUE TITLE
Data breach observed when two concurrent send message requests are made to different tenants

### ISSUE THREAD

**Issue by nagarjun-chodapaneedi** [microsoft/BotBuilder-V3#245]
## Version
3.11.0

## Describe the bug
We have observed a sporadic issue with bot builder when trying to send O365ConnectorCards to two different tenants in Microsoft teams. We tried to send two different `O365ConnectorCard`s to two different sessions but observed that the content is mixed for one of the tenant.  Text of one message is replaced with other `O365ConnectorCard's` text although the title and potentialAction are intact.  we are trying to understand if there is a session overlap in botbuilder framework. 

## To Reproduce
The issue is sporadic, we have observed this only once. Both the messages were triggered at the same time.

## Expected behavior
Content should not be overlapped between two tenant sessions.

## Screenshots
<img width="460" alt="Screenshot 2022-03-16 at 10 54 00 AM" src="https://user-images.githubusercontent.com/57436297/158522656-c553f369-f748-481f-bf2f-0b5de4586cb9.png">

**Comment by anishprasad01** [comment]
Hi @nagarjun-chodapaneedi,

Something like this might first lead to an examination of state storage. Can you tell us more about how your bot is implemented? Perhaps something in how your bot is accessing and storing state might be causing this?

In your investigations, were you able to reproduce and/or identify which functionality might be at fault? Could you share some example code relating to the offending functionality that may help us identify what might be causing this?

We need more information before we can examine this.

**Comment by nagarjun-chodapaneedi** [comment]
Hi @anishprasad01 

We are unable to reproduce this issue. This is how we are sending a message.

Building the message using:
`bot = new builder.UniversalBot(this.chatConnector); // Instance created only once`

```
const session: builder.Session // Created using bot.loadSession for every message send operation
const message: builder.Message // Created using builder.Message(session) for every message send operation
```

Message is sent using
```
session.connector.startConversation(address, async (err, response) => {
    if (err) {
        return reject(err);
    }
    session.beginDialog('*:/sendNotificationToTeams', message);
    resolve();
});
```

Dialog is defined as
```
bot.dialog('/sendNotificationToTeams',
    (session: builder.Session, message: builder.IMessage, next) => {
        session.send(message).endDialog();
    },
);
```

We can see the two messages were built in separate instances. we suspect that once we begin a dialog with `sendNotificationToTeams` there is some overlap of sessions and message objects.

**Comment by diya-biju** [comment]
@anishprasad01 The same issue has happened again when trying to send O365ConnectorCards to two different tenants in Microsoft teams. 
<img width="567" alt="Screenshot 2022-04-12 at 8 24 18 PM" src="https://user-images.githubusercontent.com/45651712/162991983-4f2c50f6-c5a6-4f82-8a68-2fd3457e6210.png">

**Comment by anishprasad01** [comment]
Please provide a specific reproducible example so we can investigate.

**Comment by diya-biju** [comment]
@anishprasad01 Not able to reproduce the issue as its sporadic.
The implementation is https://github.com/microsoft/BotBuilder-V3/issues/245#issuecomment-1070338799

**Comment by anishprasad01** [comment]
Do you have Application Insights or other logs available that may have captured useful information that might help identify the cause?

**Comment by anishprasad01** [comment]
@nagarjun-chodapaneedi, @diya-biju,

You could try creating the response message inside the callback. That should help isolate messages from each other.

Additionally, SDK V3 is officially deprecated, and thus official advice would be to upgrade to SDK V4 at your earliest convenience for the latest features and continued support.
