### ISSUE TITLE
[Skype for Business] HTML message formatting inconsistencies (macOS vs Windows)

### ISSUE THREAD

**Issue by bora89** [Microsoft/BotBuilder-V3#33]
SFB on windows:
![](https://getfile.dokpub.com/yandex/get/https://yadi.sk/i/iktc55dKjTharg)

SFB on MacOS Mojave
![](https://getfile.dokpub.com/yandex/get/https://yadi.sk/i/hexIH5v91Fy1zA)

When this inconsistency will go away finally? I have latest SFB for MacOS btw

**Comment by JasonSowers** [comment]
This is not an issue with bot framework.  This is a known issue with the SFB client on mac.  If you would like to provide feedback to the SFB team you can do so [here](https://www.skypefeedback.com/)

As a workaround you can apply the twilio workaround I outline in [this issue](https://github.com/Microsoft/BotBuilder/issues/4897#issuecomment-408559121)
