### ISSUE TITLE
[bug] [skype] [slack] GetConversationsAsync returns MethodNotAllowed

### ISSUE THREAD

**Issue by Ma3yTa** [Microsoft/BotBuilder-V3#34]
## Version
``3.16.1.38846``

## Describe the bug
``GetConversationsAsync`` returns ``MethodNotAllowed``

## To Reproduce
```csharp
try
{
                var connector = new ConnectorClient(new Uri(activity.ServiceUrl)); 
                var conversationsResponse = await connector.Conversations.GetConversationsAsync();
                await context.PostAsync(conversationsResponse.Conversations.Count.ToString());
}
catch (Exception ex)
{
                await context.PostAsync(ex.Message);
}
```

## Expected behavior
``GetConversationsAsync`` returns a list of conversations

## Screenshots
![](https://i.gyazo.com/66033f5435f99e37391fcf97f704826d.png)

[bug]
[dotnet]

**Comment by EricDahlvang** [comment]
Calls to the channels mentioned here (Skype and Slack) return a MethodNotAllowed exception.  However, I also could not get this to work with the Emulator, DirectLine or WebChat.  I also tried using v4 and Postman as well, with the same results.  DirectLine and WebChat return:

{
    "error": {
        "code": "ServiceError",
        "message": "bot channel not found"
    }
}

There is apparently an issue in the backend.  We will escalate this.

**Comment by CoHealer** [comment]
After investigation with the team it's apparent that this is only supported for DirectLine and Facebook. It is not supported for Skype and as such we're closing the issue.
