### ISSUE TITLE
A new build of BotBuilder needs to be cut and pushed to NuGet

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-V3#45]
## Version
3.16.1.xxxx has a bug introduced by the following commit
https://github.com/Microsoft/BotBuilder-V3/commit/3f6da33aff6cf89b160a438af3ae0ff68d7c3733#diff-1f91ba761477b26405ffa0278d8ace6d

This commit is being reverted, and as a result, we need to cut a new build
3.16.2.xxxx

[bug]
[dotnet]

**Comment by cleemullins** [comment]
The [3.16.2.42631 build](https://botbuilder.myget.org/gallery/botbuilder-v3-dotnet-daily) is published on the daily build feed.

The [package(s) can be seen here](https://botbuilder.myget.org/feed/botbuilder-v3-dotnet-daily/package/nuget/Microsoft.Bot.Builder/3.16.2.42631).

Next step is to regression test, then publish.

**Comment by EricDahlvang** [comment]
Closing.  This has all been completed.
