### ISSUE TITLE
Send List Template with ChannelData to Facebook Messenger returned 'Bad Request'

### ISSUE THREAD

**Issue by FengXiaohe** [Microsoft/BotBuilder-V3#46]
## Version
bot builder V3.15.2.2

## Describe the bug
Using the bot framework V3.15.2.2, I send a List Template to Face book by ChannelData, but it is failed, and I get the exception of [Operation returned an invalid status code 'BadRequest'] .
But I send the Json by curl, it was successful.

## To Reproduce
`
RootDialog.cs

    public virtual async Task ChoiceReceivedAsync(IDialogContext context, IAwaitable<Object> activity)
        {
                var message = context.MakeMessage();
                message.ChannelData = getListTemplate();
                await context.PostAsync(message);
       }

    private object getListTemplate()
        {
            ListMessenger fbmsg = new ListMessenger();
            fbmsg.ChannelData = 
                new ListMessengerChannelData
                {
                    notification_type = "NO_PUSH",
                    attachment = new ListMessengerAttachment { payload = new ListMessengerPayload()}
                };
            fbmsg.ChannelData.attachment.type = "template";
            fbmsg.ChannelData.attachment.payload.template_type = "list";
            fbmsg.ChannelData.attachment.payload.top_element_style = "compact";
            List<ListMessengerElement> e = new List<ListMessengerElement>();
            e.Add(new ListMessengerElement
            {
                title = "Classic T  Shirt Collection",
                subtitle = "See all our colors",
                image_url = "https://peterssendreceiveapp.ngrok.io/view?item=101",
                buttons = new ListPostbackButton[] { new ListPostbackButton { title ="select", type = "postback", payload = "Collection" } },
            });
            e.Add(new ListMessengerElement
            {
                title = "Classic White T Shirt",
                subtitle = "See all our colors",
                default_action = new ListMessengerAction { type = "web_url", url= "https://peterssendreceiveapp.ngrok.io/view?item=101", messenger_extensions = false, webview_height_ratio ="tall"}
            });
            e.Add(new ListMessengerElement
            {
                title = "Classic Blue T Shirt",
                subtitle = "100 Comfortable",
                image_url = "https://peterssendreceiveapp.ngrok.io/view?item=101",
                default_action = new ListMessengerAction { type = "web_url", url = "https://peterssendreceiveapp.ngrok.io/view?item=101", messenger_extensions = true, webview_height_ratio = "tall", fallback_url= "https://peterssendreceiveapp.ngrok.io/" },
                buttons = new ListPostbackButton[] { new ListPostbackButton { title = "select", type = "postback", payload= "Blue" } },
            });
            List<ListPostbackButton> bs = new List<ListPostbackButton>();
            bs.Add(new ListPostbackButton { type = "postback", title = "View More", payload = "View More" });
            fbmsg.ChannelData.attachment.payload.elements = e.ToArray();
            fbmsg.ChannelData.attachment.payload.buttons = bs.ToArray();
            return fbmsg.ChannelData;
        }`

`
 ListTemplate.cs

    public class ListMessenger
    {
        public ListMessengerChannelData ChannelData { get; set; }
    }

    public class ListMessengerChannelData
    {
        public string notification_type { get; set; }
        public ListMessengerAttachment attachment { get; set; }
    }

    public class ListMessengerAttachment
    {
        public string type { get; set; }
        public ListMessengerPayload payload { get; set; }
    }

    public class ListMessengerPayload
    {
        public string template_type { get; set; }
        public ListMessengerElement[] elements { get; set; }
        // for list only
        public string top_element_style { get; set; }
        // for list only
        public ListPostbackButton[] buttons { get; set; }
    }

    public class ListMessengerElement
    {
        public string title { get; set; }
        public string subtitle { get; set; }
        public string item_url { get; set; }
        public string image_url { get; set; }
        public ListPostbackButton[] buttons { get; set; }
        public ListMessengerAction default_action { get; set; }
    }

    public class ListUrlButton : ListMessengerAction
    {
        public string title { get; set; }
    }

    public class ListPostbackButton
    {
        public string type { get; set; }
        public string title { get; set; }
        public string payload { get; set; }
    }
    public class ListMessengerAction
    {
        public string type { get; set; }
        public string url { get; set; }
        public Boolean messenger_extensions { get; set; }
        public string webview_height_ratio { get; set; }
        public string fallback_url { get; set; }
    }
}`

`
the Json generated by Bot Framework Emulator

    "channelData": {
    "notification_type": "NO_PUSH",
    "attachment": {
      "type": "template",
      "payload": {
        "template_type": "list",
        "elements": [
          {
            "title": "Classic T  Shirt Collection",
            "subtitle": "See all our colors",
            "image_url": "https://peterssendreceiveapp.ngrok.io/view?item=101",
            "buttons": [
              {
                "type": "postback",
                "title": "select",
                "payload": "Collection"
              }
            ]
          },
          {
            "title": "Classic White T Shirt",
            "subtitle": "See all our colors",
            "default_action": {
              "type": "web_url",
              "url": "https://peterssendreceiveapp.ngrok.io/view?item=101",
              "messenger_extensions": false,
              "webview_height_ratio": "tall"
            }
          },
          {
            "title": "Classic Blue T Shirt",
            "subtitle": "100 Comfortable",
            "image_url": "https://peterssendreceiveapp.ngrok.io/view?item=101",
            "buttons": [
              {
                "type": "postback",
                "title": "select",
                "payload": "Blue"
              }
            ],
            "default_action": {
              "type": "web_url",
              "url": "https://peterssendreceiveapp.ngrok.io/view?item=101",
              "messenger_extensions": true,
              "webview_height_ratio": "tall",
              "fallback_url": "https://peterssendreceiveapp.ngrok.io/"
            }
          }
        ],
        "top_element_style": "compact",
        "buttons": [
          {
            "type": "postback",
            "title": "View More",
            "payload": "View More"
          }
        ]
      }
    }
  }

`

## Expected behavior
I hope you can help me find the problem and give me the solution if possible.

## Screenshots
![image](https://user-images.githubusercontent.com/30440909/47768580-ab213f00-dd13-11e8-8e89-c7cf7ed76ad6.png)

## Additional context

[bug]
[dotnet]

**Comment by FengXiaohe** [comment]
As the following changed, it is worked.
old   : message.ChannelData = getListTemplate();
new :  message.ChannelData = JObject.FromObject(getListTemplate());

Is there anything difference whether is there "JObject.FromObject" ?

**Comment by EricDahlvang** [comment]
Hi @FengXiaohe 

I'm glad you've got it working.

On this page, https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-channeldata?view=azure-bot-service-3.0 the documentation states: 

>  Note
> The value of an activity object's channel data property is a JSON object. Therefore, the examples in this article show the expected format of the channelData JSON property in various scenarios. To create a JSON object using .NET, use the JObject (.NET) class.
