### ISSUE TITLE
Can't loadSession from bot.on('event', event => {})

### ISSUE THREAD

**Issue by filipjakov** [Microsoft/BotBuilder-V3#51]
## Version
**Botbuilder**: 3.15.0,
**Node.js**: 8.9.0
**Running on my local machine**

## Description
The call for `builder.UniversalBot.loadSession` fails silently while called in the `builder.UniversalBot.on` handler.

## To Reproduce
1. A Directline postActivity is created on the client. A 'event' type message with text 'connect' is sent to the bot.
```
  botConnection
    .postActivity({
      from: user,
      type: 'event',
      text: 'connect'
    })
    .subscribe(
      id => console.log('Posted activity, assigned ID ', id),
      error => console.log('Error posting activity', error)
    );
``` 
2. A handler is created in the bot. It's suppose to call loadSession with the provided address recieved from the event but it never enters the callback.

```
bot.on('event', data => {
  bot.loadSession(data.address, (error, session) => {
    if (error) {
      console.error(error);
    }
    ...
  });
});
```

3. If I promisify the loadSession: 
```
bot.on('event', data => {
  const promisifyLoadSession = promisify(bot.loadSession);
  promisifyLoadSession(data.address)
    .then(_ => {
      console.log(_);
    })
    .catch(err => {
      console.error(err);
    });
});
```
I get the following catched error message and stack trace:
```
{
message: "Cannot read property 'loadSessionWithOptionalDispatch' of undefined",
stack: "TypeError: Cannot read property 'loadSessionWithOptionalDispatch' of undefined
    at UniversalBot.loadSession (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:253:14)
    at internal/util.js:227:26
    at UniversalBot.bot.on.data (/home/fbulic/Bots/Bot-HandOff/app.ts:75:5)
    at emitOne (events.js:116:13)
    at UniversalBot.emit (events.js:211:7)
    at /home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:156:31
    at /home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:427:53
    at UniversalBot.tryCatch (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:516:13)
    at next (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:427:23)
    at UniversalBot.eventMiddleware (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:430:9)
    at /home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:141:23
    at /home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:472:53
    at UniversalBot.tryCatch (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:516:13)
    at /home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:472:23
    at UniversalBot.tryCatch (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:516:13)
    at UniversalBot.lookupUser (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:459:14)
    at /home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:136:19
    at /home/fbulic/Bots/Bot-HandOff/node_modules/async/lib/async.js:181:20
    at replenish (/home/fbulic/Bots/Bot-HandOff/node_modules/async/lib/async.js:319:21)
    at /home/fbulic/Bots/Bot-HandOff/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/home/fbulic/Bots/Bot-HandOff/node_modules/async/lib/async.js:220:35)
    at UniversalBot.receive (/home/fbulic/Bots/Bot-HandOff/node_modules/botbuilder/lib/bots/UniversalBot.js:133:15)"
}
```
## Expected behavior
Should loadSession without failing silently.

[bug]
[javascript]

**Comment by nyxsys** [comment]
You mentioned `data.address` a few times in the event handler, but it doesn't look like that's defined in the activity sent, which should be the source of the immediate issue from the looks of things. 


That said, I'll take a look into why the callback is not returning the error out of `loadSession`

**Comment by filipjakov** [comment]
@nyxsys as the activity enters the bot it has some additional data/properties, one of which is the address property (implementing the botbuilder [IAddress](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iaddress.html) interface). Here is an example of a data object:

```
{
"type":"event",
"timestamp":"2018-11-03T08:47:30.4687371Z",
"name":"connect",
"text":"",
"attachments":[],
"entities":[],
"address":{"id":"6uhHKBSxVUC13WBYlzrJGR|0000000","channelId":"webchat","user":{"id":"Agent01","name":"Agent01"},"conversation":{"id":"6uhHKBSxVUC13WBYlzrJGR"},"bot":{"id":"<botId>,"name":<botNAme>},"serviceUrl":"https://directline.botframework.com/"},
"source":"webchat",
"agent":"botbuilder",
"user":{"id":"Agent01","name":"Agent01"}
}
```

**Comment by nyxsys** [comment]
For the moment I'm setting up a PR to at least add a try catch for error handling to the location that should throw the exception. I am going to dig deeper and try and find out why this is occurring at all after that.

**Comment by nyxsys** [comment]
So the error `"Cannot read property 'loadSessionWithOptionalDispatch' of undefined"` suggests that something is wrong with the initialization of the universal bot. Could you post your code where you initialize the `bot` itself?

**Comment by filipjakov** [comment]
This is the code:
```
const bot = new builder.UniversalBot(connector)
  .set('localizerSettings', {
    botLocalePath: path.join(process.cwd(), 'locale'),
    defaultLocale: 'en'
  })
  .set('persistConversationData', true)
  .set('autoBatchDelay', 0)
  .set('storage', new builder.MemoryBotStorage());
```

I've used other methods (like `send`, `on`, `dialog` ...) and everything works. This is the only exception.

**Comment by nyxsys** [comment]
I realize that, which is why its weird that the error suggests there's an issue there, going to look into it further.

**Comment by nyxsys** [comment]
I tried `bot.loadSession` on a bot on the same version of botbuilder you've listed in three locations. ` bot.on()` as well as `bot.dialog()` and `bot.use()` but I have not been able to recreate the error you are seeing, both with and without including the same bot.set() config calls you've posted. Could you try and see if you get a different result out of putting the `bot.loadSession()` call into [middleware](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-intercept-messages?view=azure-bot-service-3.0#example)  using `bot.use()`?
If that doesn't work, it might be good to see if you could put together a minimum version of your bot that can reproduce this issue.

**Comment by CoHealer** [comment]
@filipjakov, have you tried the suggestion from @nyxsys or is the issue resolved? Thx.

**Comment by CoHealer** [comment]
Closing as resolved not repro
