### ISSUE TITLE
Include SDK version identifier in User-Agent header on all calls to LUIS APIs

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotBuilder-V3#58]
Is your feature request related to a problem? Please describe.
Today, we do not have any view into LUIS traffic that are driven by botbuilder. LUIS service instruments all calls to the service and can report on User-Agent to identify the specific client.

Describe the solution you'd like
On all calls to LUIS service, include User-Agent header with the following value -
botbuilder/v3-sdk/csharp/major.minor.patch.build
botbuilder/v3-sdk/js/major.minor.patch.build

[enhancement]
[dotnet]

## Tracking Status
**Dotnet SDK**
- [x] PR
- [x] Merged

**Javascript SDK**
- [x] PR
- [x] Merged

**Comment by EricDahlvang** [comment]
https://github.com/Microsoft/botbuilder-dotnet/blob/master/doc/UserAgents.md

**Comment by vishwacsena** [comment]
Eric, I'm very much aware of the user agent doc. This issue will help us instrument bot builder calls on the LUIS service side and can provide usage across SDK, CLI tools and emulator.

**Comment by EricDahlvang** [comment]
@vishwacsena I was planning on implementing this in BotBuilder v3, and just added the link to UserAgents spec so I can refer to it when I get to this. :)

**Comment by CoHealer** [comment]
@EricDahlvang, please coordinate the change with those being done by @yshahin and @Zerryth

**Comment by EricDahlvang** [comment]
Closed the PR (format was a hack).  

@johnataylor will provide a new format for the user-agent string.

**Comment by CoHealer** [comment]
Fix checked in & merged into master.
