### ISSUE TITLE
Add alteredQuery to LUIS Result

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotBuilder-V3#64]
## Tracking Status
**Dotnet SDK**
(already exists: https://github.com/Microsoft/BotBuilder-V3/commit/e0e0d9bf5565034436cd60d05cb0d5339b01f726 )

**Javascript SDK**
- [x] PR
- [x] Merged

**Comment by CoHealer** [comment]
@EricDahlvang, per our discussion it seems like this should be done at the the same time as #63 Add Sentiment Analysis. Please confirm with @cleemullins
