### ISSUE TITLE
Node localization tests are failing

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotBuilder-V3#66]
## Version
Clean pull of the respository

## Describe the bug
Tests in Node\core\tests\localization.js are failing

## To Reproduce
1. download the source
2. npm install in core folder
3. npm run test
4. See errors

## Expected behavior
Tests all pass

## Additional context
55 passing (2m)
  23 failing

  1) localization
       should return localized prompt when found:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  2) localization
       should return random prompt for arrays:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  3) localization
       should return prompt in users preferred local:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  4) localization
       should return prompt in bots default local:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  5) localization
       should return prompt in sub-local:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  6) localization
       should fallback to bots locale:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  7) localization
       should fallback to bots locale for invalid preferredLocale:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  8) localization
       should fallback to "en" for missing bot locale:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  9) localization
       library should return libraries prompt:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  10) localization
       library should return bots overriden prompt:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  11) localization
       library should return bots prompt for missing locale:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  12) localization
       should use bots namespace for prompt:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  13) localization
       should use bots namespace for retryPrompt:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  14) localization
       should use libraries namespace for prompt:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  15) localization
       should use libraries namespace for retryPrompt:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  16) localization
       should use bots namespace for cancelAction:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  17) localization
       should use bots namespace for reloadAction:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  18) localization
       should use bots namespace for endConversationAction:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\localization.js)

  19) promptRecognizers
       should recognize a localized RegExp:

      Uncaught AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at botbuilder (tests\promptRecognizers.js:13:17)
      at next (lib\Session.js:86:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\Session.js:110:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:64:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:52:16
      at done (node_modules\async\lib\async.js:246:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:44:16
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:61:64
      at tryCallOne (node_modules\promise\lib\core.js:37:12)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\promise\lib\core.js:123:15
      at flush (node_modules\asap\raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  20) promptRecognizers
       should recognize localized choices:

      Uncaught AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at botbuilder (tests\promptRecognizers.js:42:17)
      at next (lib\Session.js:86:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\Session.js:110:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:64:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:52:16
      at done (node_modules\async\lib\async.js:246:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:44:16
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:61:64
      at tryCallOne (node_modules\promise\lib\core.js:37:12)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\promise\lib\core.js:123:15
      at flush (node_modules\asap\raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  21) promptRecognizers
       should recognize a localized choice using a synonym:

      Uncaught AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at botbuilder (tests\promptRecognizers.js:59:17)
      at next (lib\Session.js:86:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\Session.js:110:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:64:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:52:16
      at done (node_modules\async\lib\async.js:246:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:44:16
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:61:64
      at tryCallOne (node_modules\promise\lib\core.js:37:12)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\promise\lib\core.js:123:15
      at flush (node_modules\asap\raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  22) promptRecognizers
       should recognize a localized choice without any synonyms:

      Uncaught AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at botbuilder (tests\promptRecognizers.js:75:17)
      at next (lib\Session.js:86:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\Session.js:110:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:64:17
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:52:16
      at done (node_modules\async\lib\async.js:246:17)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\async\lib\async.js:44:16
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\lib\DefaultLocalizer.js:61:64
      at tryCallOne (node_modules\promise\lib\core.js:37:12)
      at C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\node_modules\promise\lib\core.js:123:15
      at flush (node_modules\asap\raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  23) recognizers
       should match a LocalizedRegExpRecognizer:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\work\v3\clean10.30.2018\BotBuilder-V3\Node\core\tests\recognizers.js)

[bug]
[javascript]

**Comment by CoHealer** [comment]
@EricDahlvang, please investigate and fix

**Comment by EricDahlvang** [comment]
User err! 👎
