### ISSUE TITLE
Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by LlewellynJones** [Microsoft/BotBuilder-V3#67]
## Version
3.17.0.42969

## Describe the bug

Microsoft.Bot.Connector.ErrorResponseException
operation returned an invalid status code 'Unauthorized'

## To Reproduce
If the application hasn't been used for an hour or more there is an authorization error at the start of a conversation with the app. If the error is ignore the conversation continues normally.

## Expected behavior
Expect the conversation to start without an error.

Error Details:

[{"parsedStack":[{"assembly":"Microsoft.Bot.Connector,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Connector.BotState+<SetPrivateConversationDataWithHttpMessagesAsync>d__11.MoveNext","level":0,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":1,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":2,"line":0},{"assembly":"Microsoft.Bot.Connector,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Connector.BotStateExtensions+<SetPrivateConversationDataAsync>d__13.MoveNext","level":3,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":4,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":5,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore+<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d__3.MoveNext","level":6,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":7,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":8,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore+<Save>d__10.MoveNext","level":9,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":10,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":11,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore+<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-FlushAsync>d__5.MoveNext","level":12,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":13,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":14,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1+<FlushAsync>d__9.MoveNext","level":15,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":16,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":17,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.DialogTaskManagerBotDataLoader+<FlushAsync>d__12.MoveNext","level":18,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":19,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":20,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask+<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext","level":21,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":22,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":23,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask+<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext","level":24,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":25,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":26,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.SerializeByConversation+<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext","level":27,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":28,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":29,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser+<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext","level":30,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser+<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext","level":31,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":32,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":33,"line":0},{"assembly":"Microsoft.Bot.Builder,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Internals.LogPostToBot+<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext","level":34,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":35,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":36,"line":0},{"assembly":"Microsoft.Bot.Builder.Autofac,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Conversation+<SendAsync>d__11.MoveNext","level":37,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":38,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":39,"line":0},{"assembly":"Microsoft.Bot.Builder.Autofac,   Version=3.17.0.42969, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Dialogs.Conversation+<SendAsync>d__6.MoveNext","level":40,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":41,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":42,"line":0},{"assembly":"Bot   Application1, Version=1.0.0.0, Culture=neutral,   PublicKeyToken=null","method":"RiBot.MessagesController+<Post>d__3.MoveNext","level":43,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":44,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":45,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__3`1.MoveNext","level":46,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":47,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":48,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__0.MoveNext","level":49,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":50,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":51,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext","level":52,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext","level":53,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":54,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":55,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__0.MoveNext","level":56,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":57,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":58,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__2.MoveNext","level":59,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":60,"line":0},{"assembly":"mscorlib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":61,"line":0},{"assembly":"System.Web.Http,   Version=5.2.3.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__1.MoveNext","level":62,"line":0}],"outerId":"0","message":"Operation   returned an invalid status code   '0'","type":"Microsoft.Bot.Connector.ErrorResponseException","id":"138365"}]
--

[bug]
[dotnet]

**Comment by CoHealer** [comment]
Fixed with 3.19 release
