### ISSUE TITLE
IMPLEMENTING LUIS WITH OPTIONS

### ISSUE THREAD

**Issue by pepefrog69** [Microsoft/BotBuilder-V3#70]
Im using Azure to develop my bot. Im trying to create a bot using LUIS where if i ask it for a scan, it should give me back four types of analysis for a scan for eg: metrology, porosity, reverse engineering and wall thickness. Then i can choose an option form it.I feel like this is a very easy thing to do but im very new to computer programming, node.js. and bots.

This is how far ive gotten, i dont know how to progress from here,
code:
```js
bot.dialog('CT scan',
    (session) => {
        session.send('You asked for a CT scan', session.message.text);
        session.endDIalog();
    }   
).triggerAction({
    matches: 'CT scan'
})
```
I also found this on another page in this forum. Can i implement this code in my code to get the result i want and how do i do it?
code:

===================================================================
```js
var DialogLabels = {
    Hotels: 'Hotels',
    Flights: 'Flights',
    Support: 'Support'
};

var bot = new builder.UniversalBot(connector, [
    function (session) {
        // prompt for search option
        builder.Prompts.choice(
            session,
            'Are you looking for a flight or a hotel?',
            [DialogLabels.Flights, DialogLabels.Hotels],
            {
                maxRetries: 3,
                retryPrompt: 'Not a valid option'
            });
    },
    function (session, result) {
        if (!result.response) {
            // exhausted attemps and no selection, start over
            session.send('Ooops! Too many attemps :( But don\'t worry, I\'m handling that exception and you can try again!');
            return session.endDialog();
        }

        // on error, start over
        session.on('error', function (err) {
            session.send('Failed with message: %s', err.message);
            session.endDialog();
        });

        // continue on proper dialog
        var selection = result.response.entity;
        switch (selection) {
            case DialogLabels.Flights:
                return session.beginDialog('flights');
            case DialogLabels.Hotels:
                return session.beginDialog('hotels');
        }
    }
]);
```

**Comment by sgellock** [comment]
this is pretty old.

**Comment by EricDahlvang** [comment]
Hi @pepefrog69 

Let me see if I understand your scenario correctly.  You have four types of scans: metrology, porosity, reverse engineering and wall thickness.  It sounds like you want LUIS to help determine which type of scan the user is requesting.  If that is the case, you can create a LUIS model that has a 'CT Scan' intent and a list type entity of 'Scan Type' with metrology, porosity, reverse engineering and wall thickness as values.  (I've created a model with this intent and entity here: https://gist.github.com/EricDahlvang/8e6817121be69fe8726eb5be83611ec5 )

With this LUIS model, your CT Scan dialog would probably look something like this:

```js

bot.dialog('CT Scan', [
  function (session, args, next) {
    debugger;
    let foundScanType = builder.EntityRecognizer.findEntity(args.intent.entities, 'Scan Type');
    
    if(foundScanType){
      session.dialogData.scanType = foundScanType.entity;
      next();
    }
    else{      
      //missing scan type from luis entities
      //(user may have said 'perform scan', or something without Scan Type)
      var prompt =  "What type of scan would you like to perform?";
      builder.Prompts.choice(session, prompt, "metrology|porosity|reverse engineering|wall thickness", { listStyle: builder.ListStyle.button });
    }
  },
  function (session, args) {
      let scanType = session.dialogData.scanType || args.response.entity;

      //execute analysis logic of type scanType here
      session.endDialog("Got it. Performing scan of type: %s...", scanType);
  }    
]).triggerAction({ matches: 'CT Scan' });

```

This will handle cases where the user specifies the scan type, and when they do not, the bot will ask for it.

**Comment by EricDahlvang** [comment]
@pepefrog69 I'm closing this issue.  If you have future questions about LUIS or the Bot Framework, please direct them to StackOverflow https://stackoverflow.com/questions/tagged/botframework  The Bot Framework team prefers to use the GitHub repositories for Feature Requests and Bug Reports.
