### ISSUE TITLE
bot not responding with Citrix Secure Web Mobile browser

### ISSUE THREAD

**Issue by ShujaathKhan** [Microsoft/BotBuilder-V3#77]
## Version
- V3.
- .NET framework
- Directline Implementation

## Describe the bug
Bot is totally not functional in Citrix secure web.
Where as bot is working fine Chrome mobile browser
We're are using in secure brower to secure with authentication.

## To Reproduce
1.  Open the bot link in **Citrix Secure browser in Mobile**
2.  Say hi to bot
3. You'll not see any message sent back by bot

## Expected behavior
Bot should work the way it function in desktop browser

## Additional context
Needed to respond in Citrix Secure web Mobile reason being user is authenticated and context of current user is set.
 [Link to app Citrix Secure web mobile](https://play.google.com/store/apps/details?id=com.citrix.browser.droid&hl=en_IN)

**Comment by EricDahlvang** [comment]
HI @ShujaathKhan 

This is the BotBuilder-V3 repository.  Please direct your issue to the WebChat repository here: https://github.com/Microsoft/BotFramework-WebChat/issues
