### ISSUE TITLE
BotAuthenticator failed to authenticate incoming request

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder-V3#89]
Since several hours my bot (both staging and production) can't authenticate incoming requests (without any changes in it). In Application Insights I see the following failures:

![application insight](https://user-images.githubusercontent.com/5601143/49558119-abb08500-f912-11e8-87f5-b8a5eec25fed.jpg)

**Comment by EricDahlvang** [comment]
Where is the bot hosted?

 These changes have recently been applied: https://blog.botframework.com/2018/11/06/announcement-azure-bot-service-enforcing-transport-layer-security-tls-1-2/  could they be affecting your bot?

**Comment by mitkodi** [comment]
@EricDahlvang, the production bot is hosted on Windows Server 2012 and the staging on Windows Server 2008 R2 SP1 (KB3140245 is already installed).

**Comment by mitkodi** [comment]
I solved the problem by enabling strong encryption for all .NET application:
```
# set strong cryptography on 64 bit .Net Framework (version 4 and above)
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

# set strong cryptography on 32 bit .Net Framework (version 4 and above)
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord 
```
