### ISSUE TITLE
Bots not working. Possible issue with Azure Bot Channel connectors. Error: "There was an error sending this message to your bot: HTTP status code Unauthorized" ( from 7.12.2018 to 11.12.2018)

### ISSUE THREAD

**Issue by poltyo** [Microsoft/BotBuilder-V3#93]
Bots didn't work for a couple of days returning "There was an error sending this message to your bot: HTTP Status code Unauthorized". We suspect there might have been an issue with Bot Channel connectors. Could you please confirm? 

## Screenshots
![image 2018-12-11 11 40 42](https://user-images.githubusercontent.com/25149659/49788138-989a1c80-fd39-11e8-8f2c-9d27a748cf93.jpg)

[bug]
[dotnet]

**Comment by jwiley84** [comment]
Similar to https://github.com/Microsoft/BotBuilder-V3/issues/92

**Comment by MarynaParyvai** [comment]
Hi and thanks for getting back! We have multiple bots. One of them is s6t-bot-49-s6test-testbot: MsAppId: e8295088-3ce2-40dc-8fc7-ab167416f81d

Hope you can help!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by fercom** [comment]
this worked for me: https://social.msdn.microsoft.com/Forums/en-US/90af15ce-16ce-49e1-980c-b3dba7b9e8a7/my-chatbots-suddenly-dont-work-on-facebook?forum=windowsazurewebsitespreview&prof=required

**Comment by poltyo** [comment]
> Hi @poltyo ,
> 
> You wrote "Bots didn't work for a couple of days returning "There was an error sending this message to your bot: HTTP Status code Unauthorized". We suspect there might have been an issue with Bot Channel connectors. Could you please confirm?"
> 
> Are you still seeing this or was it transient? Thx.

Bots started to work again yesterday 12/11, but we still need to investigate the issue as our clients have been affected

**Comment by poltyo** [comment]
> this worked for me: https://social.msdn.microsoft.com/Forums/en-US/90af15ce-16ce-49e1-980c-b3dba7b9e8a7/my-chatbots-suddenly-dont-work-on-facebook?forum=windowsazurewebsitespreview&prof=required

We had our servers configured to accept TLS 1.2 when bots stopped working and didn't change anything with TLS when started working again

**Comment by CoHealer** [comment]
Thanks. I'm glad this resolved your issue. I'll pass the information from codeshare and see if we can get the blog posting updated to reflect this.

**Comment by poltyo** [comment]
> Thanks. I'm glad this resolved your issue. I'll pass the information from codeshare and see if we can get the blog posting updated to reflect this.

Hi CoHealer!

While the issue has fixed itself, we need to investigate what has caused the issue to create a report for our clients. 

As I have said, bots started to work on 12/11, after glitches 12/7-12/11 and we haven't done anything to either break or fix them neither have we changed the server's configuration. As i said **We had our servers configured to accept TLS 1.2 when bots stopped working**
