### ISSUE TITLE
Skype Markdown do not show Images

### ISSUE THREAD

**Issue by taranais** [Microsoft/BotBuilder-V3#95]
## Version
SDK 3.19.1.44133

## Describe the bug
Skype Channel do not render markdown correctly

## To Reproduce

markdown sample:
![markdown](https://user-images.githubusercontent.com/859916/50001724-08a8dc80-ff9e-11e8-8e96-ee8ee28b17eb.png)

## Expected behavior
Same render as Webchat:

![webchat](https://user-images.githubusercontent.com/859916/50001753-1fe7ca00-ff9e-11e8-9c85-b95c31ae42c4.png)

## Screenshots
![skype](https://user-images.githubusercontent.com/859916/50001754-237b5100-ff9e-11e8-98a5-7d73fd5b19ca.png)

**Comment by EricDahlvang** [comment]
Hello @taranais 

Not all channels support every form of Markdown.  This Channel Inspector is a little out of date, but still useful: https://docs.botframework.com/en-us/channel-inspector/channels/Skype?f=Markdown&e=example1  

Also, with Skype specifically, there has historically been different levels of Markdown support depending on which Skype client is being used.  Which client and version are you using?

**Comment by taranais** [comment]
Android and Windows Desktop Store.
Some months ago it render ok, dont know when it stop render it.

third screen on inspector show skype rendering markdown images [link](https://docs.botframework.com/en-us/images/inspector/Skype/Markdown/example3.png)

**Comment by EricDahlvang** [comment]
Are you able to provide the version number for which Skype client version properly rendered the markdown?

Also, please share the actual markdown or a small example that will reproduce the problem.

**Comment by CoHealer** [comment]
@taranais, please respond or will close as inactive.

**Comment by taranais** [comment]
Any inline image markdown send on postAsyn Will show this issue

''''
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
''''

**Comment by CoHealer** [comment]
Apologies for the delayed response @taranais . Per the Skype team this is by design; it's not supported.
