### ISSUE TITLE
502 Bad Gateway when deploy bot framework to Azure in Testing in Web Chat

### ISSUE THREAD

**Issue by pancongying** [Microsoft/BotBuilder-V3#96]
## Version
SDK: V3
.NET

## Describe the bug
I'm still struggeling with deploy mijn bot framework app to Azure. I was succes to publish the application in VS en also succesfully tested in Emulator using the messaging endpoint. But when I created a new Web App Bot in Azure Portal en configure the endpoint, app id en key. Then it gave me a 502 Bad Gateway error in Testing in Web Chat. 
I also tried a simple bot framework application that juist using the standaard bot framework template. 
So I dont know how to fix it. Can anyone help me?

## Screenshots
![image](https://user-images.githubusercontent.com/29035467/50082853-4605a800-01f2-11e9-84a8-60fd683729e3.png)
![image](https://user-images.githubusercontent.com/29035467/50082765-08a11a80-01f2-11e9-85df-654260d36720.png)
![image](https://user-images.githubusercontent.com/29035467/50082819-2ec6ba80-01f2-11e9-8f36-97077e10a2dc.png)
![image](https://user-images.githubusercontent.com/29035467/50082868-4f8f1000-01f2-11e9-9e0b-46dca3911251.png)
![image](https://user-images.githubusercontent.com/29035467/50082892-659cd080-01f2-11e9-8b85-e34f2d012804.png)

[bug]
[dotnet]

**Comment by pancongying** [comment]
Can anybody help me or give me some tips?

**Comment by EricDahlvang** [comment]
Based on this image:
![image](https://user-images.githubusercontent.com/11055362/50114111-97189a80-01f8-11e9-8e62-491444955016.png)

The bot is using the default state service, which has been deprecated.  Please try adding an **IBotDataStore<BotData>** implementation, such as **InMemoryDataStore**:

```cs

Conversation.UpdateContainer(builder =>
{
    var memorystore = new InMemoryDataStore();
    builder
        .RegisterType<InMemoryDataStore>()
        .Keyed<IBotDataStore<BotData>>(typeof(ConnectorStore));

    builder.Register(c => new CachingBotDataStore(memorystore, CachingBotDataStoreConsistencyPolicy.ETagBasedConsistency))
        .As<IBotDataStore<BotData>>()
        .AsSelf()
        .SingleInstance();

});
```

This blog post discusses the deprecation of the default state service: https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/

**Comment by pancongying** [comment]
Hi @EricDahlvang. Thanks for your replying. With your feedback I changed the Global.asax.cs based on this website: https://blog.botframework.com/2017/07/18/saving-state-azure-extensions/
Now I have my custom storage using cosmos db and Emulator doesnt give me the message you showed above any more. So I think it is succusfully implemented. 
![image](https://user-images.githubusercontent.com/29035467/50151260-a9f6a200-02c0-11e9-9f63-7bd8e16a771a.png)

But it still doesnt work in Test in Web Chat. Do you have some more idea?

**Comment by EricDahlvang** [comment]
Based on the images, your messaging endpoint is https://agendabotapp.azurewebsites.net/api/messages  ... does the Application Settings for AgendaBotApp have the MicrosoftAppId and MicrosoftAppPassword for the bot?

**Comment by pancongying** [comment]
Hi, @EricDahlvang. I have configured the MicrosoftAppId en MicrosoftAppPassword in Application Settings (see the 3rd image i posted).
Is this issue caused by the version of bot framework that i used (bot framework v3)? Because i tried to create a new Web App Bot en used the default messaging endpoint en it worked fine. But when i changed the messaging endpoint to  https://agendabotapp.azurewebsites.net/api/messages then it did not work anymore.

**Comment by EricDahlvang** [comment]
The 3rd image above is for ordinaagendabot-b16f not for agendabotapp.  Whatever web application the bot's messaging endpoint is using needs to have the  MicrosoftAppId and MicrosoftAppPassword in Application Settings.

**Comment by pancongying** [comment]
![image](https://user-images.githubusercontent.com/29035467/50289862-532ccc00-046a-11e9-8d05-edc027c55fa8.png)
Hi @EricDahlvang Thanks a lot. It works finally en it was a zo simple error. haha. Thanks!
