### ISSUE TITLE
FormFlow: Navigation step responds incorrectly when multiple fields match user input

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotBuilder-V3#99]
## Version

3.19.1

## Describe the bug

A navigation step in a FormFlow form dialog will give choices of what field to navigate to. Sometimes the terms used to identify fields will match more than one field (ex: "name" could match both first name and last name). In other steps, FormFlow asks for [clarification](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow?view=azure-bot-service-3.0#clarify-user-input) when it gets ambiguous input. But in the navigation step, it does not ask for clarification.

Instead, the dialog displays the prompt for the first field in the list of fields that match the user input. That by itself wouldn't be much of a bug at all, but the bug is actually that even though the prompt for the field has been displayed, FormFlow continues to respond to user input as though it's still on the navigation step! If you enter something that isn't a valid navigation choice, it will say "Your text" is not a field name option. If you enter a valid navigation choice, it will navigate there. It's still on the navigation step even though it displayed the prompt for a field as though it's on a different step.

![formflowambiguousnavigation](https://user-images.githubusercontent.com/41968495/50378217-cad13700-05e1-11e9-8147-f2265a078194.jpg)

Here's an example of code that can reproduce this behavior. If you get to the navigation step and type "ambiguous" then it will navigate to the AmbiguousString field but then immediately act as though it's still on the navigation step because it's really confused about which step it was supposed to go to.

```c#
public DateTime AmbiguousDate { get; set; }
public string AmbiguousString { get; set; }

public static IForm<MyClass> BuildForm()
{
	var builder = new FormBuilder<MyClass>()
		.Field(nameof(AmbiguousString))
		.Field(nameof(AmbiguousDate))
		.Confirm("Okay?");

	return builder.Build();
}
```

I suspect the reason behind this has to do with the way FormFlow identifies the current step as the navigation step. In the [source code](https://github.com/Microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormDialog.cs#L334), you can see that FormFlow determines that it's on the navigation step when there's more than one choice for the next step:

```c#
if (next.Direction == StepDirection.Named && next.Names.Length > 1)
{
	// We need to choose between multiple next steps
	bool start = (_formState.Next == null);
	_formState.Next = next;
	step = new NavigationStep<T>(_form.Steps[_formState.Step].Name, _form, _state, _formState);
```

This may seem like a non-issue because the navigation step provides buttons that the user will surely click on. However, the text provided by the buttons is still not unambiguous in cases where one field's description contains the entirety of another field's description. So if you click the button to navigate to the Birthday field, the FormFlow dialog will still be confused about whether it should navigate to the Birthday field or the MothersBirthday field.

## To Reproduce

1. Create a FormFlow form with at least two fields whose names or descriptions or terms partially overlap (meaning they have some of the same words in them), along with a confirmation step
2. While running the bot, observe how those fields respond to acceptable and unacceptable input
3. When you reach the confirmation step, say "no" to activate the navigation step
4. Enter text that doesn't match any of the available fields (perhaps "asdf") and observe the navigation step's not-understood message
5. Enter text that matches more than one of the available fields
6. Observe that the prompt makes it appear that you've navigated to one of those fields
7. Enter acceptable and unacceptable input and observe that the validator responds as though you're on the navigation step and not the field step that had its prompt displayed

## Expected behavior

There are a few possible "correct" behaviors we might expect from FormFlow. The simplest solution would be to have the navigation step just navigate to one of the matched fields like it appears to be doing now, but also to do it correctly so that you can enter a value for that field and not have FormFlow act like it's still on the navigation step. Another solution would be to have FormFlow ask for clarification if the user enters something ambiguous, like how the sample sandwich bot asks if you mean green bell peppers or banana peppers if you just say "peppers." Of course that would be annoying if one of the buttons produced an ambiguous message and then FormFlow had to ask for clarification when the user had already picked one of the supposedly unambiguous options presented to them. So I think the best solution would be to ensure that button clicks always produce a response that can only apply to one unique field and none of the others. That solution may have to be combined with one of the other solutions to still account for the user entering text instead of clicking a button.

## Additional context

One thing that helped me diagnose this problem was using a [custom prompter](https://github.com/v-kydela/BotBlog/blob/master/Blog%20-%20Making%20your%20own%20Prompter.md). When I set a breakpoint in the PromptAsync delegate I could break on every step of the dialog and then I could see what step the dialog was on. When it gives the fake field prompt I can see that it's on that field's step, but then when I enter incorrect input I can see that when it responds it's on the navigation step.

One clue that might help find out what's going on is that when you enter "help" during the erroneous pseudo-navigation step, it displays the help for the navigation step but then repeats the prompt for the fake field step. The help command is meant to repeat the prompt after giving help so the prompt is expected, but I thought perhaps it would show the prompt for the navigation step. Instead, it again shows the prompt for the field that it didn't actually navigate to.

![formflownavigationhelpwithwrongprompt](https://user-images.githubusercontent.com/41968495/50378912-746bf480-05f1-11e9-859a-9b1a58aa72b4.jpg)

Another clue is that this bug occurs even when one of the ambiguously-named fields is optional and currently inactive at the time the navigation step is reached! An inactive field cannot be navigated to from the navigation step, and yet still the field can contribute to the navigation step's confusion about which step to navigate to. So if I have AmbiguousName and AmbiguousDate and AmbiguousDate is inactive and I enter "ambiguous" at the navigation step, the navigation step will get confused even though only one of those fields is an actual option. This indicates that the process of recognizing the names of fields based on user input takes inactive fields into consideration, so that process isn't done in the same way as the process of validating whether the user entered one of the actual choices.

[bug]
[dotnet]

**Comment by v-kydela** [comment]
Actually, now I'm second-guessing myself. Upon further testing, it seems the bug can manifest when you enter a partial field name at the navigation step even if that input isn't ambiguous. So this may have more to do with partial input than ambiguous field names. Perhaps it has to do with the dialog using field terms to determine the next prompt but expecting the field's full description in order to navigate to that field.

**Comment by CoHealer** [comment]
BY design and a work around is available. Not doing enhancements to v3.

**Comment by v-kydela** [comment]
I'm sorry but what is the workaround?
